name: Hello DevOps CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "✅ Hello DevOps from ${{ github.actor }}!"
